// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8Qf7uh-0aq6tbsNox4nxwpPOaXDtM8M',
    appId: '1:4662603549:web:a3e78744812472bc70bbf4',
    messagingSenderId: '4662603549',
    projectId: 'xpense-49e12',
    authDomain: 'xpense-49e12.firebaseapp.com',
    storageBucket: 'xpense-49e12.firebasestorage.app',
    measurementId: 'G-ZXD1MEG9KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNkmzcGt1ERntnm3N-0VHVX2s6B-Vf0bA',
    appId: '1:4662603549:android:cc2ba088864cd1ba70bbf4',
    messagingSenderId: '4662603549',
    projectId: 'xpense-49e12',
    storageBucket: 'xpense-49e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLX0eZLnKqXOS35tluVX1WVLfWoGT8b8',
    appId: '1:4662603549:ios:1bac61b8643ced2470bbf4',
    messagingSenderId: '4662603549',
    projectId: 'xpense-49e12',
    storageBucket: 'xpense-49e12.firebasestorage.app',
    iosBundleId: 'com.example.xpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLX0eZLnKqXOS35tluVX1WVLfWoGT8b8',
    appId: '1:4662603549:ios:1bac61b8643ced2470bbf4',
    messagingSenderId: '4662603549',
    projectId: 'xpense-49e12',
    storageBucket: 'xpense-49e12.firebasestorage.app',
    iosBundleId: 'com.example.xpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8Qf7uh-0aq6tbsNox4nxwpPOaXDtM8M',
    appId: '1:4662603549:web:43da7dd5bdd4d94a70bbf4',
    messagingSenderId: '4662603549',
    projectId: 'xpense-49e12',
    authDomain: 'xpense-49e12.firebaseapp.com',
    storageBucket: 'xpense-49e12.firebasestorage.app',
    measurementId: 'G-65G677Q8N8',
  );

}